### ISSUE TITLE
Enabling tweak injection breaks application permissions

### ISSUE THREAD

**Issue by runmain** [roothide/Bootstrap#2]
After respring, the mobile app cannot receive push notifications, and the app cannot be found in the settings

disable tweak and re-able tweek enabler , app can  receive push notifications

**Comment by dleovl** [comment]
Any mention on widgets, icons, and normal permissions? Why do these break?

**Comment by dleovl** [comment]
Bit of a side effect, but tweaks that list user applications (namely for enabling tweak functionality) will cease to function unless given a 'global injection' (inject into all apps) feature. iGameGod as an example. You can't enable tweak injection into an app (that is now system) and use a tweak that specifically targets a user application. There is no point in time where both can occur, being tweak injection, and the tweak recognizing the user app and enabling its functionality. Most tweaks are globally injected, not requiring you to choose specific applications in its preferences.

**Comment by dleovl** [comment]
com.apple.Preferences cannot be launched through spotlight or shortcuts with tweak injection enabled (tested on A13 17.0 with PreferenceLoader and known working tweaks that contain preference bundles). Launches fine from homescreen.

**Comment by dleovl** [comment]
> > well, it does not get notifications after rebooting the device or rebuilding the apps, and we'll try to fix that.
> 
> 
> 
> So have you found out the solution to that issue yet? The push notifications of App Store apps after enabling the tweak.

There is currently no permanent fix.

**Comment by dleovl** [comment]
This issue is kind of tricky. For one, the issue with notifications has been fixed. On the other hand, rebuilding applications in the Bootstrap application will essentially reset permissions for applications, prompting you to allow them when next requested by the application, though it seems to be only all TrollStore apps.

Will close. Mitigation to this issue is as simple as setting up the applications again, or simply not rebuilding the applications, as issues that would be fixed by this button are usually fixable by other means.
